# Generated by Django 6.0.1 on 2026-01-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_id', models.CharField(help_text='ID do domínio na API SMTP.dev', max_length=255, unique=True)),
                ('domain', models.CharField(help_text='Nome do domínio (ex: example.com)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Domínio está ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['-is_active', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_id', models.CharField(help_text='ID da conta na API SMTP.dev', max_length=255, unique=True)),
                ('address', models.EmailField(help_text='Endereço completo (ex: user@example.com)', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Senha da conta', max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Último uso da conta', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Conta disponível para uso?')),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='Quando a sessão atual expira', null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='Conta em cooldown até esta data (2h após expiração)', null=True)),
                ('last_session_key', models.CharField(blank=True, help_text='Session key do último usuário (para permitir reutilização)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Última sincronização com a API externa', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.domain')),
            ],
            options={
                'verbose_name': 'Conta de Email',
                'verbose_name_plural': 'Contas de Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_id', models.CharField(help_text='ID da mensagem na API SMTP.dev', max_length=255, unique=True)),
                ('from_address', models.EmailField(help_text='Email do remetente', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Nome do remetente', max_length=255)),
                ('to_addresses', models.JSONField(default=list, help_text='Lista de destinatários')),
                ('cc_addresses', models.JSONField(blank=True, default=list, help_text='Lista de CC')),
                ('bcc_addresses', models.JSONField(blank=True, default=list, help_text='Lista de BCC')),
                ('subject', models.CharField(blank=True, help_text='Assunto do email', max_length=500)),
                ('text', models.TextField(blank=True, help_text='Conteúdo em texto puro')),
                ('html', models.TextField(blank=True, help_text='Conteúdo em HTML')),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Metadados dos anexos')),
                ('is_read', models.BooleanField(default=False, help_text='Mensagem foi lida?')),
                ('is_flagged', models.BooleanField(default=False, help_text='Mensagem marcada?')),
                ('received_at', models.DateTimeField(help_text='Quando a mensagem foi recebida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.emailaccount')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['is_available', 'last_used_at'], name='core_emaila_is_avai_046aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['address'], name='core_emaila_address_237f59_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'received_at'], name='core_messag_account_e57a64_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'is_read'], name='core_messag_account_5b5691_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-received_at'], name='core_messag_receive_7de5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['smtp_id'], name='core_messag_smtp_id_f04026_idx'),
        ),
    ]
